language: node_js
node_js:
  - 14.16.0
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run next export
  - touch out/.nojekyll
deploy:
  provider: pages
  github_token: $github_token
  local_dir: out
    on:
    branch: master